# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ROSS
email: dross3@live.unc.edu
description: The Life of Ross
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://DROSS21.github.io" # the base hostname & protocol for your site
#twitter_username: hemang_kumar
github_username: DROSS21

# Build settings
markdown: kramdown
